### ISSUE TITLE
Компонент отказывается работать

### ISSUE THREAD

**Issue by iqubik** [ananyevgv/esphome-components#1]
Привет. Компонент почему-то отказывается работать. Собираю такой код.
```
substitutions:
  mq7_name: "MQ7"
  mq7_id: "mq7"

#not works from readme!!!:
#external_components:
  #source: github://ananyevgv/esphome-components
  #components: [mq]
  #refresh: 0s

# external_components: #working 010125
#   - source:
#       type: git
#       url: https://github.com/ananyevgv/esphome-components
#     components: [mq]

external_components: #also works try local
  - source: 
      type: local
      path: custom_components

web_server:
  port: 80
  local: true
  #auth:
    #username: !secret web_server_username
    #password: !secret web_server_password  

esphome:
  name: cosenser
  friendly_name: COsenser

esp32:
  board: esp32dev
  framework:
    type: arduino

logger:
  level: ERROR
  baud_rate: 0

ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Cosenser ap"
    password: !secret wifi_password

# captive_portal:

output:
  - platform: gpio
    pin: ${mq7_heater_pin}
    id: ${mq7_id}_heater_pin

# interval:
#   - interval: 150s
#     then:
#       - switch.turn_on: ${mq7_id}_heater
#       - logger.log: "${mq7_name}: The sensor is heating!"
#       - delay: 55s
#       - switch.turn_off: ${mq7_id}_heater
#       - logger.log: "${mq7_name}: The sensor is measuring!"
#       - delay: 90s
#       - if:
#           condition:
#             - switch.is_off: ${mq7_id}_heater
#           then:
#             - component.update: ${mq7_id}_raw
#             - logger.log: "${mq7_name}: Done"
#             - switch.turn_on: ${mq7_id}_heater
#             - delay: 5s

switch:
  - platform: output
    name: "${mq7_name} Heater"
    icon: mdi:fire
    entity_category: diagnostic
    disabled_by_default: True
    id: ${mq7_id}_heater
    output: ${mq7_id}_heater_pin

text_sensor:
  - platform: template
    name: "ESP32 Chip ID"
    lambda: |-
      uint64_t chipid = ESP.getEfuseMac();
      char chipid_str[13];
      snprintf(chipid_str, sizeof(chipid_str), "%04X%08X", (uint16_t)(chipid >> 32), (uint32_t)chipid);
      return {chipid_str};
    update_interval: 60s
    entity_category: diagnostic

sensor:
  - platform: mq
    model: MQ7
    pin: GPIO33
    update_interval: 145s
    sensor_lpg:
      name: Sensor LPG
    sensor_ch4:
      name: Sensor CH4
    sensor_co:
      name: Sensor CO
    sensor_alcohol:
      name: Sensor ALCOHOL
    sensor_h2:
      name: Sensor H2
```
